export default {
  "nav": {
    "ranking": "Ranking",
    "modelMarket": "Model Market",
    "requestResponseLogs": "Request Capture"
  },
  "dashboard": {
    "tokenRankingTitle": "Ranking",
    "tokenRankingSubtitle": "Top 10 users by token usage for today, this week, and this month",
    "tokenRankingEmpty": "No ranking data yet",
    "rankingPlaceholder": "Waiting for a challenger",
    "rankingFirstDescription": "GPU Slayer",
    "rankingSecondDescription": "Fan Overdrive",
    "rankingThirdDescription": "CPU Alarm",
    "rankingToday": "Today",
    "rankingWeek": "This Week",
    "rankingMonth": "This Month"
  },
  "usageRanking": {
    "title": "Ranking",
    "description": "View the top 10 users by token usage for today, this week, and this month"
  },
  "channelStatus": {
    "requestWindows": {
      "title": "Request Windows",
      "requests": "requests",
      "success": "Success rate",
      "errors": "Error rate",
      "errorRate": "Error rate",
      "avgHourlyRequests": "Avg hourly",
      "level": {
        "idle": "Idle",
        "normal": "Normal",
        "busy": "Busy",
        "congested": "Congested"
      }
    }
  },
  "modelMarket": {
    "title": "Model Market",
    "description": "Shows available models by accessible group. Each card highlights the group name, current multiplier, and admin-configured recommendation score.",
    "badge": "Generated by accessible groups",
    "searchPlaceholder": "Search models, groups, or providers...",
    "allProviders": "All Providers",
    "availableModels": "Available models in this group",
    "emptyTitle": "No available models",
    "emptyDescription": "No matching groups or models were found, or no models are configured for your accessible groups yet.",
    "exclusive": "Exclusive Group",
    "public": "Public Group",
    "modelCount": "{count} models",
    "pricing": {
      "openHint": "Click to view model price reference",
      "title": "{group} Price Reference",
      "titleFallback": "Price Reference",
      "rateHint": "Prices below include the current group multiplier and are for reference only.",
      "noPricing": "Pricing not configured",
      "billingModeToken": "Per Token",
      "billingModePerRequest": "Per Request",
      "billingModeImage": "Per Image",
      "inputPrice": "Input",
      "outputPrice": "Output",
      "cacheWritePrice": "Cache Write",
      "cacheReadPrice": "Cache Read",
      "imageOutputPrice": "Image Output",
      "perRequestPrice": "Per Request",
      "perImagePrice": "Per Image",
      "intervals": "Tiered Pricing",
      "unitPerMillion": "/ 1M tokens",
      "unitPerRequest": "/ request",
      "unitPerImage": "/ image"
    },
    "stats": {
      "models": "Models",
      "providers": "Providers",
      "groups": "Groups"
    },
    "recommendation": {
      "normal": "Normal",
      "moderate": "Moderate",
      "recommended": "Recommended",
      "super": "Super Value"
    }
  },
  "availableChannels": {
    "pricing": {
      "perImagePrice": "Per Image",
      "unitPerImage": "/ image"
    }
  },
  "redeem": {
    "buyActivationCode": "Buy activation code"
  },
  "admin": {
    "requestResponseLogs": {
      "title": "Request/Response Capture",
      "description": "View complete request and response data exchanged between users and the site"
    },
    "groups": {
      "recommendation": {
        "label": "Model Market recommendation label",
        "labelPlaceholder": "e.g. Best Value / Stable Pick",
        "labelHint": "Leave empty to use the automatic label based on multiplier.",
        "stars": "Model Market stars",
        "starsHint": "Range 3-5 stars. Minimum 3 stars; higher stars use stronger recommendation colors."
      }
    },
    "accounts": {
      "openai": {
        "codexImageGenerationBridge": "Codex image-generation bridge",
        "codexImageGenerationBridgeDesc": "Account policy takes precedence over channel and global settings. Only controls whether Codex requests through the /responses text endpoint receive the image_generation tool; standalone image-generation endpoints are unaffected.",
        "codexImageGenerationBridgeInherit": "Follow channel",
        "codexImageGenerationBridgeInheritDesc": "Do not write an account override; use the channel or global policy.",
        "codexImageGenerationBridgeEnabled": "Force on",
        "codexImageGenerationBridgeEnabledDesc": "Allow image tool injection for Codex /responses requests.",
        "codexImageGenerationBridgeDisabled": "Force off",
        "codexImageGenerationBridgeDisabledDesc": "Block image tool injection for Codex /responses requests.",
        "codexImageGenerationBridgeBadgeInherit": "Channel policy",
        "codexImageGenerationBridgeBadgeEnabled": "Account on",
        "codexImageGenerationBridgeBadgeDisabled": "Account off"
      }
    },
    "settings": {
      "tabs": {
        "notifications": "Notifications/Webhook"
      },
      "webhook": {
        "title": "System Notification Webhook",
        "description": "Configure system event webhooks. Redeem-code usage is sent asynchronously; this is not a payment callback.",
        "enable": "Enable webhook notifications",
        "enableHint": "When enabled, successful redeem-code usage sends a notification to the configured webhook URL.",
        "url": "Webhook URL",
        "urlHint": "Supports Feishu/Lark bot URLs and generic HTTP(S) endpoints that accept JSON.",
        "format": "Message format",
        "timeout": "Request timeout (seconds)",
        "bearerToken": "Bearer Token (optional)",
        "bearerTokenPlaceholder": "Optional, used as Authorization: Bearer ...",
        "bearerTokenConfiguredPlaceholder": "********",
        "bearerTokenHint": "Leave empty if the target endpoint does not require auth.",
        "bearerTokenConfiguredHint": "Token is configured. Leave empty to keep the current value.",
        "eventHint": "Note: this is not a payment callback. It listens to system events. Successful redeem-code usage emits redeem_code.used with code type, value, validity days, user, and related fields."
      },
      "site": {
        "contactQrCodeUrl": "Contact QR Code",
        "contactQrCodeUrlPlaceholder": "https://example.com/contact-qrcode.png or data:image/...",
        "contactQrCodeUrlHint": "Legacy field: used as the webmaster contact QR code.",
        "contactWebmasterQrCode": "Webmaster Contact QR Code",
        "contactWebmasterQrCodeHint": "Upload a local PNG/JPG. It is saved as data:image and shown under Webmaster Contact in the Contact Us dialog.",
        "contactGroupQrCode": "Group Chat QR Code",
        "contactGroupQrCodeHint": "Upload a local PNG/JPG. It is saved as data:image and shown under Join Group Chat in the Contact Us dialog.",
        "activationCodePurchaseUrl": "Activation Code Purchase URL",
        "activationCodePurchaseUrlPlaceholder": "https://example.com/buy-code",
        "activationCodePurchaseUrlHint": "Purchase link shown on the redeem page. Leave empty to hide it."
      }
    }
  }
} as const
